### ISSUE TITLE
Adding support for EKS_ROLE_ARN users

### ISSUE THREAD

**Issue by idobleicher** [ianbelcher/eks-kubectl-action#12]
I have added the code for that but I cant open a pr to that.

`  eks_role_arn:
    description: EKS role arn that allow access eks cluster (Mostly happen when you create your cluster with CDK).
    required: false`
    
   `if [ -n "${INPUT_EKS_ROLE_ARN}"]; then
  aws eks update-kubeconfig --name "${INPUT_CLUSTER_NAME}" --role-arn "${INPUT_EKS_ROLE_ARN}"
else 
  aws eks update-kubeconfig --name "${INPUT_CLUSTER_NAME}"
fi`

`          eks_role_arn: $ {{ secrets.EKS_ROLE_ARN }}
`

**Comment by ianbelcher** [comment]
Thanks for this work @iuyt9003 and really appreciate the second follow up PR to fix the issue. :-)

Hope you have a good holiday period and new years.

**Comment by idobleicher** [comment]
Yay! Super happy to contribute :) hope you liked my addon 👯
