### ISSUE TITLE
Failure to download image

### ISSUE THREAD

**Issue by imberda** [ianbelcher/eks-kubectl-action#17]
As of today, when running the action, its no longer possible to download the associated docker image:

```
Pull down action image 'ghcr.io/ianbelcher/eks-kubectl-action:latest'
/usr/bin/docker pull ghcr.io/ianbelcher/eks-kubectl-action:latest
latest: Pulling from ianbelcher/eks-kubectl-action
540db60ca938: Pulling fs layer
d037ddac5dde: Pulling fs layer
cbc5b43a0be9: Pulling fs layer
6e5772212e62: Waiting
74916cdbf5e7: Waiting
f1850f7408de: Waiting
26bd607dacd2: Waiting
bbc67a1f0da4: Waiting
66066a9236cf: Waiting
e29256e467d2: Waiting
96b64e0d2413: Waiting
c662527bf7dc: Waiting
error pulling image configuration: download failed after attempts=1: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```

**Comment by lauren-themis** [comment]
Saw the same, but reran my failing action just now and it worked 🤷‍♀️

**Comment by ianbelcher** [comment]
Thanks for posting this information @imberda and @lauren-themis.

The error appears to be an issue with your ability to access gh packages, not so much this package. Taking a quick look now.

**Comment by ianbelcher** [comment]
Appears there was 'degraded performance' with gh packages in the last hour or two which is the likely explanation and why it's now working again for you @lauren-themis.

Is your action working again now as well @imberda?
