### ISSUE TITLE
Action build failing 

### ISSUE THREAD

**Issue by lehno** [ianbelcher/eks-kubectl-action#2]
Action build is failing with python errors, any of my deploys wont work.

**Comment by buckion** [comment]
I'm experiencing the same issue

**Comment by buckion** [comment]
Looking at the dockerfile and the logs, it appears as though the dependencies of the kubernetes release have moved past those that can be built in the docker environment set up, the fix is probably as simple as bumping the dependency of the container.

**Comment by buckion** [comment]
@lehno Yup confirmed that as the fix on my fork https://github.com/dmaxtec/eks-kubectl-action

**Comment by ianbelcher** [comment]
Thanks for looking into this @buckion!

If you wanted to set up a quick PR I'll merge it in, otherwise I can make that change in about 10 minutes?

**Comment by ianbelcher** [comment]
Just merged #3 which solves this issue. Hopefully everything should be fixed and working now. Please reopen if there are still issues.

**Comment by lehno** [comment]
Tried this morning, all working, Thank you guys
