### ISSUE TITLE
adding optional 'Profile' argument to entrypoint.sh

### ISSUE THREAD

**Issue by socraticDevBlog** [ianbelcher/eks-kubectl-action#6]
tl;dr : new feature proposal : being able to impersonate a role when updating kubeconfig

In order to be able to use `eks-kubectl-action` for my current project, I need to be able to impersonate a specific IAM Role.

Basically, I'd need to be able to execute `update-kubeconfig` with an extra argument (in file `entrypoint.sh`): 

```
aws eks --region ca-central-1 update-kubeconfig --name "My-Cluster" --profile "aSpecificIAMRole" 
```

Is it a feature you'd be interested in?

**Comment by socraticDevBlog** [comment]
omg! it's bigger than i expected. nevermind ;)

**Comment by ianbelcher** [comment]
I’m currently offline but this doesn’t seem to be that much of a change? I
should be able to take a look in a few hours.
