### ISSUE TITLE
How to run a few kubectl commands?

### ISSUE THREAD

**Issue by vitalykarasik** [ianbelcher/eks-kubectl-action#8]
Sorry if this offtopic, but I couldn't find how to execute a few kubectl command? Like "update image ; get pods"?

TIA, Vitaly

**Comment by ianbelcher** [comment]
Hi Vitaly,

Separating the different calls into separate steps will work. Is there a use case where you would need the kubectl command to be run as single step?

**Comment by vitalykarasik** [comment]
Ian, thank you!
 >  Is there a use case where you would need the kubectl command to be run as single step?
I'd like to check deployment status in the same step, by running "kubectl describe deployments" for example.
